### ISSUE TITLE
tox tests always output the same version numbers

### ISSUE THREAD

**Issue by johentsch** [DCMLab/dimcat#48]
Running `tox` is supposed to run the test as a product of Python versions `(3.10, 3.11)` and of pandas versions `(1.5.3, latest)`.

After each of the four tests the output shows the same version numbers: 
![image](https://github.com/DCMLab/dimcat/assets/42718519/4a0665f3-f26a-4486-abd2-cc56a37a953d)

@huguesdevimeux would it be possible to entire the pip freeze for the environment in question each time?

**Comment by huguesdevimeux** [comment]
Yes, it's totally possible, but I was afraid that it would produce a very long output. 

I will take a look at it shortly, that's a weird issue
