### ISSUE TITLE
Automated tests not triggered upon push into open PR

### ISSUE THREAD

**Issue by johentsch** [DCMLab/dimcat#51]
Before 8e2262f, when pushing changes into an open PR, the tests got triggered twice, once by the `push` event and once by the `pull_request` event.

But for some reason, now the tests are not triggered at all in the case in question. See for example #47. In your #50 on the other hand the tests ran twice for the first commit and once for the following ones.

Would you happen to know the canonical triggers to specify so that the tests run exactly once every time, @huguesdevimeux? Is it maybe that this event also needs a push specifier? 

https://github.com/DCMLab/dimcat/blob/d4531d567ec73acaba5311ce87ef193f837abf5c/.github/workflows/ci.yml#L6

**Comment by huguesdevimeux** [comment]
Hello, 

The issue comes from the fact that you are making your PR from a fork, while I was merging a branch from the base repository - which I wasn't aware of, but I shouldn't be doing that.
