### ISSUE TITLE
Dependency conflict jsonschema

### ISSUE THREAD

**Issue by MirjamVisscher** [DCMLab/dimcat#53]
There is a dependency conflict for jsonschema. jupyter-events 0.8.0 requires jsonschema[format-nongpl]>=4.18.0 while frictionless 5.16.0 requires jsonschema<4.18

Code needed to replicate the issue:
> pip install dimcat

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyter-events 0.8.0 requires jsonschema[format-nongpl]>=4.18.0, but you have jsonschema 4.17.3 which is incompatible.
jupyterlab-server 2.25.1 requires jsonschema>=4.18.0, but you have jsonschema 4.17.3 which is incompatible.

> pip install --upgrade jsonschema
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
frictionless 5.16.0 requires jsonschema<4.18, but you have jsonschema 4.20.0 which is incompatible.

**Comment by johentsch** [comment]
Thanks for reporting @MirjamVisscher. This conflict is currently not resolvable but is not a hinderance.
